### PR TITLE
Support third party metrics in model server

### PR DESCRIPTION
**Pull request by LeiZhou-97**
End user may have some specific metrics that are not included in kepler, so this patch enhance the model server to collect third party metrics

Limitation:
the pattern of thirdparty_metrics must align with kepler container level metrics, which contains containerid, containername and etc. Because it can reuse kepler container power consumption as output for training.
```
thridparty_metrics + other metrics(like cgroup....) -> input
container power consumption from kepler -> output
```

### CODE REVIEW

**Comment by sunya-ch** [comment]
Thank you for your contribution. 
I believe it is related to the issue https://github.com/sustainable-computing-io/kepler-model-server/issues/181.
This is very promising to dynamically add third-party feature group. 
If all test is pass, this PR looks good to me. 

In my understanding, it will be set only when we set it in cmd argument. 
I would be nice if we can also call `update_thirdparty_metrics` when the third party metrics are set via environment or configmap for the model server, online trainer, and estimator sidecar. However, this could be done on the another PR if you don't want to implement it here.

**Comment by LeiZhou-97** [comment]
@sunya-ch 
Thanks for your quick reply. I will update my code to fix the CI issue.

In my original design, I want to add the metrics into configmap and watch it in realtime. If it changes, the model server will update accordingly. This approach has some more effort and I have no much time. I can move it to the environment to align with existing configs as an work around.

**Comment by sunya-ch** [comment]
> @sunya-ch Thanks for your quick reply. I will update my code to fix the CI issue.
> 
> In my original design, I want to add the metrics into configmap and watch it in realtime. If it changes, the model server will update accordingly. This approach has some more effort and I have no much time. I can move it to the environment to align with existing configs as an work around.

Thanks a lot. Nice work.

Actually, if you call the function `getConfig` in [util module ](https://github.com/sustainable-computing-io/kepler-model-server/blob/9f670d228beca0583a9dce8da4b47f731a08fc82/src/util/config.py#L43), it will try reading environment value or config data if set.  

You may define a key for the third-party metric such as `THIRD_PARTY_METRICS` then call getConfig('THIRD_PARTY_METRICS', "") to get the value. This key will be applied for both direct environment variable and config map data without any modification.

**Comment by LeiZhou-97** [comment]
I've updated my code. Now it can get thirdparty_metrics from cmd and configmap/environment.

I also run the unittest on my server and it passed. It my need your approve to re-trigger the GHA.

**Pull request merged**
