### PR TITLE
fix: enhance cluster setup script for model training

### PR DESCRIPTION
**Pull request by vprashar2929**
This commit improves the script used to setup the cluster for model training.
Key changes:
- Improved the readability through proper formatting
- Fixed `cluster_up` failure due to incorrect `KUBECONFIG` setting
- Applied shellcheck for script linting
- Exported only necessary variables to avoid environment pollution
- Removed `kubectl` command installation as it is already a pre-requisite
- Updated to `v0.0.5` for local-dev-cluster and `latest` for model-server image
- Updated the README to reflect these changes

**Note: This doesn't change the existing definitions to keep the scope minimum**

### CODE REVIEW

**Comment by sunya-ch** [comment]
@vprashar2929  Thank you so much for the PR. It has some conflict on readme I updated in https://github.com/sustainable-computing-io/kepler-model-server/pull/312. 
I like your format more but we need the content from #312. Can we have #312 merge first and rebase this PR from there.

**Comment by vprashar2929** [comment]
@sunya-ch Is installation of kubectl required [here](https://github.com/sustainable-computing-io/kepler-model-training-playbook/blob/14faa85b626e5b97c67a6d1fbc6ea2b051e7af01/roles/instance_collect_role/tasks/main.yml#L23) to be done by `script. sh`? My PR removes it as it was added as one of the pre-requisites

**Comment by sunya-ch** [comment]
> @sunya-ch Is installation of kubectl required [here](https://github.com/sustainable-computing-io/kepler-model-training-playbook/blob/14faa85b626e5b97c67a6d1fbc6ea2b051e7af01/roles/instance_collect_role/tasks/main.yml#L23) to be done by `script. sh`? My PR removes it as it was added as one of the pre-requisites

We can remove kubectl installation from script.sh to reduce code to maintain.

**Review by sunya-ch — APPROVED** [review]
LGTM. This will be merged next after the fix from the PR https://github.com/sustainable-computing-io/kepler-model-server/pull/331 since currently the CI will be alway failed on push.

**Pull request merged**
