### PR TITLE
Update energy source rapl to intel_rapl

### PR DESCRIPTION
**Pull request by Yanbo0101**
Align with metrics exported by Kepler (refer to https://github.com/sustainable-computing-io/kepler/pull/1089).

### CODE REVIEW

**Comment by sunya-ch** [comment]
Thank you for the PR. It seems that the test is failed due to unavailability of model on kepler-model-db. 
Would you mind me pending this PR after uploading the new model for v0.7 soon this week?

**Comment by Yanbo0101** [comment]
> Thank you for the PR. It seems that the test is failed due to unavailability of model on kepler-model-db. Would you mind me pending this PR after uploading the new model for v0.7 soon this week?

Sure. Thanks for your review.

**Comment by sunya-ch** [comment]
Sorry for confusing you. I'm now working on refactoring CI to remove dependency of kepler-model-db (https://github.com/sustainable-computing-io/kepler-model-server/issues/220). I will merge your PR first and rebase mine on top of that.

**Comment by Yanbo0101** [comment]
> Sorry for confusing you. I'm now working on refactoring CI to remove dependency of kepler-model-db (#220). I will merge your PR first and rebase mine on top of that.

It doesn't matter. And would you mind update rapl in this [line](https://github.com/sustainable-computing-io/kepler-model-server/blob/main/cmd/cmd_util.py#L64)  in your PRs? I'm sorry for leaving it out.

**Pull request merged**
